# Маппинг: tennis_data_odds (eng) -> backtest_tennis_matches (rus)
TENNIS_DATA_TO_BETZ = {
    "Abanda F.": "Франсуаза Абанда",
    "Agamenone F.": "Франко Агаменоне",
    "Ahn K.": "Ан К.",
    "Aiava D.": "Дестани Айява",
    "Ajdukovic D.": "Айдукович Д.",
    "Albot R.": "Албот Р.",
    "Alcaraz C.": "Карлос Алькарас",
    "Alexandrova E.": "Александрова Е.",
    "Altmaier D.": "Альтмайер Д.",
    "Anderson K.": "Андерсон К.",
    "Andreescu B.": "Андрееску Б.В.",
    "Andreeva E.": "Андреева Э.",
    "Andreeva M.": "Мирра Андреева",
    "Andreozzi G.": "Андреоцци Г.",
    "Andujar P.": "Андухар П.",
    "Anisimova A.": "Аманда Анисимова",
    "Arango E.": "Эмилиана Аранго",
    "Arnaldi M.": "Маттео Арнальди",
    "Atmane T.": "Теренс Атман",
    "Auger-Aliassime F.": "Феликс Оже-Альяссим",
    "Avanesyan E.": "Элина Аванесян",
    "Azarenka V.": "Азаренка В.",
    "Babos T.": "Бабош Т.",
    "Back D.": "Дарвин Бланч",
    "Badosa P.": "Бадоса П.",
    "Baez S.": "Баез С.",
    "Bagnis F.": "Багнис Ф.",
    "Bai Z.": "Жиль Арно Байи",
    "Baindl K.": "Катерина Байндл",
    "Baptiste H.": "Баптист Х.",
    "Bara I.": "Бара И.М.",
    "Barrere G.": "Баррер Г.",
    "Barrios M.": "Моник Барри",
    "Barthel M.": "Бартел М.",
    "Bartunkova N.": "Никола Бартункова",
    "Barty A.": "Барти Э.",
    "Basavareddy N.": "Нишеш Басаваредди",
    "Basilashvili N.": "Басилашвили Н.",
    "Bautista Agut R.": "Баутиста Агут Р.",
    "Bedene A.": "Альяж Бедене",
    "Begu I.": "Бегу И.-К.",
    "Bejlek S.": "Сара Бейлек",
    "Bektas E.": "Бектас Э.",
    "Bellier A.": "Антуан Белье",
    "Bellucci M.": "Маттиа Беллуччи",
    "Bencic B.": "Белинда Бенчич",
    "Berankis R.": "Беранкис Р.",
    "Bergs Z.": "Бергс З.",
    "Berrettini M.": "Берреттини М.",
    "Bertens K.": "Бертенс К.",
    "Birrell K.": "Биррелл К.",
    "Bjorklund M.": "Бьорклунд М.",
    "Blanch Dar.": "Дарвин Бланч",
    "Blanchet U.": "Бланч У.",
    "Blinkova A.": "Анна Блинкова",
    "Blockx A.": "Александер Блокс",
    "Bogdan A.": "Ана Богдан",
    "Boisson L.": "Лоис Буассон",
    "Bolsova A.": "Анастасия Соболева",
    "Bolt A.": "Алекс Болт",
    "Bondar A.": "Анна Бондар",
    "Bonzi B.": "Бенжамен Бонзи",
    "Borg L.": "Лео Борг",
    "Borges N.": "Боргиш Н.",
    "Bouchard E.": "Бушар Э.",
    "Boulter K.": "Боультер K.",
    "Bouzkova M.": "Мария Боузкова",
    "Boyer T.": "Тристан Бойер",
    "Brady J.": "Дженнифер Брэйди",
    "Brengle M.": "Бренгл М.",
    "Broady L.": "Броуди Л.",
    "Bronzetti L.": "Бронцетти Л.",
    "Brooksby J.": "Джаред Бруксби",
    "Brouwer G.": "Гейс Брауэр",
    "Bu Y.": "Бу Ю",
    "Bublik A.": "Александр Бублик",
    "Bucsa C.": "Букса Кр.",
    "Budkov Kjaer N.": "Акугуе Ноха Н.",
    "Burel C.": "Бурель К.",
    "Burrage J.": "Жасмин Берредж",
    "Burruchaga R.": "Роман Андрес Бурручага",
    "Buzarnescu M.": "Бузарнеску М.",
    "Cachin P.": "Качин П.",
    "Carballes Baena R.": "Баутиста Агут Р.",
    "Carle M.": "Мария Лурдес Карле",
    "Carreno Busta P.": "Мартинес Портеро П.",
    "Caruso S.": "Карузо С.",
    "Cazaux A.": "Артур Казо",
    "Cecchinato M.": "Марко Чеккинато",
    "Cerundolo F.": "Серундоло Ф.",
    "Cerundolo J.M.": "Серундоло Ф.",
    "Chardy J.": "Александр Ричард",
    "Choinski J.": "Чоински Дж.",
    "Chwalinska M.": "Майя Хвалинска",
    "Cilic M.": "Марин Чилич",
    "Cina F.": "Федерико Чина",
    "Cirstea S.": "Кирстя С.",
    "Cobolli F.": "Коболли Ф.",
    "Cocciaretto E.": "Коччаретто Э.",
    "Collignon R.": "Рафаэль Коллиньон",
    "Collins D.": "Даниэль Коллинс",
    "Comesana F.": "Франсиско Комесана",
    "Contreras Gomez F.": "Ди Лоренцо Ф.",
    "Coria F.": "Кориа Ф.",
    "Coric B.": "Борна Чорич",
    "Cornet A.": "Ализе Корне",
    "Cressy M.": "Кресси М.",
    "Cristian J.": "Жаклин Кристиан",
    "Cuevas P.": "Куэвас П.",
    "Damm M.": "Мартин Дамм",
    "Daniel T.": "Даниель Т.",
    "Danilovic O.": "Данилович О.",
    "Darderi L.": "Лучано Дардери",
    "Dart H.": "Дарт Х.",
    "Davidovich Fokina A.": "Давидович Фокина А.",
    "Davis L.": "Дэвис Л.",
    "Day K.": "Кайла Дэй",
    "De Minaur A.": "Давидович Фокина А.",
    "Delbonis F.": "Дельбонис Ф.",
    "Dellien H.": "Дельен Ю.",
    "Denolly C.": "Корантен Денолли",
    "Diallo G.": "Габриэль Диалло",
    "Diaz Acosta F.": "Ди Лоренцо Ф.",
    "Dimitrov G.": "Григор Димитров",
    "Diyas Z.": "Дияс З.",
    "Djere L.": "Дьере Л.",
    "Djokovic N.": "Джокович Н.",
    "Dodig M.": "Матей Додиг",
    "Dodin O.": "Додин О.",
    "Doi M.": "Дои М.",
    "Dolehide C.": "Долехайд К.",
    "Dostanic S.": "Стефан Достанич",
    "Draper J.": "Джек Дрэйпер",
    "Droguet T.": "Титуан Дроге",
    "Duckworth J.": "Дакворт Дж.",
    "Dzumhur D.": "Дамир Джумхур",
    "Eala A.": "Александра Эала",
    "Edmund K.": "Кайл Эдмунд",
    "Engel J.": "Джастин Энгель",
    "Erjavec V.": "Вероника Эрьявец",
    "Erler A.": "Александер Эрлер",
    "Errani S.": "Сара Эррани",
    "Escobedo E.": "Эрнесто Эскобедо",
    "Etcheverry T.": "Томас Этчеверри",
    "Eubanks C.": "Кристофер Юбенкс",
    "Evans D.": "Дэниел Эванс",
    "Faria J.": "Жайме Фариа",
    "Fearnley J.": "Алёна Фалей",
    "Federer R.": "Федерер Р.",
    "Fernandez L.A.": "Лейла Фернандес",
    "Ferro F.": "Ферро Ф.",
    "Fery A.": "Анна Фрей",
    "Fett J.": "Фетт Я.",
    "Ficovich J.P.": "Фикович Х.П.",
    "Fils A.": "Артюр Фис",
    "Flipkens K.": "Кирстен Флипкенс",
    "Fognini F.": "Фабио Фоньини",
    "Fonseca J.": "Жуан Фонсека",
    "Fourlis J.": "Джейми Фурлис",
    "Fratangelo B.": "Бьорн Фратанджело",
    "Frech M.": "Фрех М.",
    "Friedsam A.L.": "Фридсам А.-Л.",
    "Fritz T.": "Тейлор Фриц",
    "Fruhvirtova B.": "Бренда Фрухвиртова",
    "Fruhvirtova L.": "Линда Фрухвиртова",
    "Fucsovics M.": "Мартон Фучович",
    "Gadecki O.": "Оливия Гадеки",
    "Gaio F.": "Гайо Ф.",
    "Gakhov I.": "Гахов И.",
    "Galan D.E.": "Даниель Элаи Галан",
    "Galarneau A.": "Алексис Галарно",
    "Galfi D.": "Галфи Д.",
    "Garcia C.": "Андреа Ласаро Гарсия",
    "Garin C.": "Гарин К.",
    "Garland J.": "Джоанна Гарланд",
    "Gasanova A.": "Анастасия Гасанова",
    "Gasquet R.": "Гаске Р.",
    "Gaston H.": "Гастон Ю.",
    "Gaubas V.": "Вилиус Гаубас",
    "Gauff C.": "Гауфф К.",
    "Gavrilova D.": "Гаврилова Д.",
    "Gea A.": "Адхитья Ганесан",
    "Gerasimov E.": "Герасимов Е.",
    "Giannessi A.": "Алессандро Джаннесси",
    "Gibson T.": "Талия Гибсон",
    "Gigante M.": "Маттео Гиганте",
    "Giorgi C.": "Камила Джорджи",
    "Giron M.": "Джирон M.",
    "Goffin D.": "Гоффин Д.",
    "Gojo B.": "Борна Гойо",
    "Gojowczyk P.": "Гоёвчик П.",
    "Golubic V.": "Виктория Голубич",
    "Gombos N.": "Гомбош Н.",
    "Gomez E.": "Гомес Эм.",
    "Gomez F.": "Федерико Агустин Гомес",
    "Gomez F.A.": "Федерико Агустин Гомес",
    "Grabher J.": "Грабер Ю.",
    "Gracheva V.": "Грачева В.",
    "Grammatikopoulou V.": "Валентини Грамматикопулу",
    "Gray A.": "Аластер Грэй",
    "Grenier H.": "Гренье Ю.",
    "Griekspoor T.": "Грикспор Т.",
    "Habib H.": "Хабиб Х.",
    "Haddad Maia B.": "Ван Де Зандшульп Б.",
    "Halep S.": "Симона Халеп",
    "Halys Q.": "Хали К.",
    "Han N.L.": "Лакиса Хан",
    "Hanatani N.": "Наги Ханатани",
    "Hanfmann Y.": "Янник Ханфман",
    "Hardt N.": "Ник Ардт",
    "Harris B.": "Билли Харрис",
    "Harris L.": "Ллойд Харрис",
    "Harrison C.": "Кристиан Харрисон",
    "Harrison Ca.": "Кристиан Харрисон",
    "Hartono A.": "Арианне Хартоно",
    "Herbert P.": "Пьер-Юг Эрбер",
    "Herbert P.H.": "Пьер-Юг Эрбер",
    "Hercog P.": "Полона Херцог",
    "Hibino N.": "Нао Хибино",
    "Hijikata R.": "Ринки Хидзиката",
    "Hoang A.": "Оан А.",
    "Holmgren A.": "Август Холмгрен",
    "Holt B.": "Брэндон Холт",
    "Hon P.": "Присцилла Хон",
    "Hontama M.": "Маи Хонтама",
    "Hruncakova V.": "Виктория Грунчакова",
    "Hsieh S.W.": "Се Су-Вэй",
    "Hsu Y.": "Ху Ю",
    "Huesler M.A.": "Марк-Андреа Хюслер",
    "Humbert U.": "Умбер У.",
    "Hunter S.": "Сторм Хантер",
    "Hurkacz H.": "Хуберт Хуркач",
    "Inglis M.": "Инглис М.",
    "Isner J.": "Джон Изнер",
    "Ito A.": "Аои Ито",
    "Ivashka I.": "Ивашка И.",
    "Jabeur O.": "Жабер O.",
    "Jang S.": "Вивиан Янг",
    "Jaziri M.": "Жазири М.",
    "Jimenez Kasintseva V.": "Хименес Касинцева В.",
    "Jodar R.": "Рафаэль Ходар",
    "Johnson S.": "Джонсон С.",
    "Jones E.": "Гомес Эм.",
    "Jones F.": "Лопес Ф.",
    "Jovic I.": "Ива Йович",
    "Juvan K.": "Кайя Юван",
    "Kachmazov A.": "Алибек Качмазов",
    "Kalieva E.": "Эльвина Калиева",
    "Kalinina A.": "Ангелина Калинина",
    "Kalinskaya A.": "Анна Калинская",
    "Kanepi K.": "Кайя Канепи",
    "Karatsev A.": "Аслан Карацев",
    "Kartal S.": "Сонай Картал",
    "Kasatkina D.": "Дарья Касаткина",
    "Kawa K.": "Кава К.",
    "Kecmanovic M.": "Кечманович М.",
    "Kenin S.": "Кенин С.",
    "Kerber A.": "Анжелика Кербер",
    "Kessler M.": "Маккартни Кесслер",
    "Keys M.": "Александер Вейс",
    "Khachanov K.": "Карен Хачанов",
    "Klein L.": "Кенин С.",
    "Klimovicova L.": "Линда Климовичова",
    "Koepfer D.": "Копфер Д.",
    "Kohlschreiber P.": "Кольшрайбер Ф.",
    "Kokkinakis T.": "Коккинакис Т.",
    "Kolar Z.": "Колар З.",
    "Konjuh A.": "Ана Конюх",
    "Konta J.": "Конта Дж.",
    "Kontaveit A.": "Анетт Контавейт",
    "Kopriva V.": "Вит Коприва",
    "Korda S.": "Корда С.",
    "Korneeva A.": "Алина Корнеева",
    "Korpatsch T.": "Корпач Т.",
    "Kostyuk M.": "Костюк М.",
    "Kotov P.": "Котов П.",
    "Kouame M.": "Мойзе Куаме",
    "Kovacevic A.": "Александар Ковачевич",
    "Kovalik J.": "Йозеф Ковалик",
    "Kovinic D.": "Данка Ковинич",
    "Kozlov S.": "Козлов С.",
    "Krajinovic F.": "Краинович Ф.",
    "Krejcikova B.": "Барбора Крейчикова",
    "Krueger A.": "Крюгер М.",
    "Krueger M.": "Крюгер М.",
    "Krunic A.": "Александра Крунич",
    "Kubler J.": "Джейсон Кублер",
    "Kucova K.": "Кристина Кучова",
    "Kudermetova P.": "Полина Кудерметова",
    "Kudermetova V.": "Вероника Кудерметова",
    "Kudla D.": "Денис Кудла",
    "Kukushkin M.": "Кукушкин М.",
    "Kumar O.": "Омни Кумар",
    "Kung L.": "Кунг Л.",
    "Kuzmova V.": "Кузмова В.",
    "Kuznetsova S.": "Кузнецова С.",
    "Kvitova P.": "Квитова П.",
    "Kwon S.W.": "Присцилла Хон",
    "Kyrgios N.": "Киргиос Н.",
    "Laaksonen H.": "Лааксонен Х.",
    "Lacko L.": "Лацко Л.",
    "Lajovic D.": "Душан Лайович",
    "Lamens S.": "Сюзан Ламенс",
    "Landaluce M.": "Мартин Ландалус",
    "Lehecka J.": "Иржи Легечка",
    "Lepchenko V.": "Варвара Лепченко",
    "Lestienne C.": "Констан Лестьенн",
    "Li A.": "Габриэла Ли",
    "Linette M.": "Линетте М.",
    "Lisicki S.": "Сабин Лисицки",
    "Liu C.": "Чжу Линь",
    "Llamas Ruiz P.": "Мартинес Портеро П.",
    "Lopez F.": "Лопес Ф.",
    "Lu Y.": "Клер Лю",
    "Lys E.": "Ева Лис",
    "Machac T.": "Махач Т.",
    "Maestrelli F.": "Франческо Маэстрелли",
    "Mager G.": "Майер Л.",
    "Mandlik E.": "Элизабет Мандлик",
    "Mannarino A.": "Адриан Маннарино",
    "Marcinko P.": "Петра Марцинко",
    "Maria T.": "Мария Т.",
    "Marino R.": "Марино Р.",
    "Marozsan F.": "Фабиан Марожан",
    "Marterer M.": "Максимилиан Мартерер",
    "Martic P.": "Мартич П.",
    "Martin A.": "Альваро Лопес Сан Мартин",
    "Martincova T.": "Мартинцова Т.",
    "Martinez P.": "Ариана Герлингс Мартинес",
    "Masarova R.": "Масарова Р.",
    "Mattek-Sands B.": "Бетани Маттек-Сандс",
    "Mayot H.": "Арольд Майо",
    "Mboko V.": "Виктория Мбоко",
    "McDonald M.": "Макдональд М.",
    "Mcdonald M.": "Макдональд М.",
    "Medjedovic H.": "Хамад Меджедович",
    "Medvedev D.": "Даниил Медведев",
    "Meligeni Alves F.": "Ди Лоренцо Ф.",
    "Mensik J.": "Менсик Я.",
    "Mertens E.": "Мертенс Э.",
    "Michelsen A.": "Алекс Микелсен",
    "Millman J.": "Джон Миллман",
    "Minella M.": "Минелла М.",
    "Minnen G.": "Грет Миннен",
    "Misolic F.": "Филип Мисолич",
    "Miyazaki Y.": "Юрико Миядзаки",
    "Mladenovic K.": "Кристина Младенович",
    "Mmoh M.": "Майкл Ммо",
    "Mochizuki S.": "Синтаро Мотидзуки",
    "Molcan A.": "Алекс Молчан",
    "Monfils G.": "Монфилс Г.",
    "Monteiro T.": "Монтейро Т.",
    "Montgomery R.": "Монтгомери Р.",
    "Moreno De Alboran N.": "Акугуе Ноха Н.",
    "Moutet C.": "Корантен Муте",
    "Mpetshi G.": "Го Мэйци",
    "Muchova K.": "Каролина Мухова",
    "Muguruza G.": "Гарбинье Мугуруса",
    "Muhammad A.": "Мухаммад А.",
    "Muller A.": "Александр Мюллер",
    "Munar J.": "Мур Т.",
    "Murray A.": "Арольд Майо",
    "Musetti L.": "Лоренцо Музетти",
    "Nadal R.": "Надаль Р.",
    "Nagal S.": "Нагаль С.",
    "Nakashima B.": "Брэндон Накашима",
    "Napolitano S.": "Стефано Наполитано",
    "Nardi L.": "Лука Нарди",
    "Nava E.": "Эдуардо Нава",
    "Navarro E.": "Наварро Э.",
    "Navone M.": "Мариано Навоне",
    "Neumayer L.": "Майер Л.",
    "Ngounoue C.": "Клерви Нгуну",
    "Nishikori K.": "Кэй Нисикори",
    "Nishioka Y.": "Ёсихито Нисиока",
    "Norrie C.": "Кэмерон Норри",
    "Noskova L.": "Линда Носкова",
    "Novak D.": "Деннис Новак",
    "Ofner S.": "Офнер С.",
    "Olivieri G.": "Дженаро Оливьери",
    "Opelka R.": "Опелка Р.",
    "Osaka N.": "Наоми Осака",
    "Osorio M.": "Момоко Кобори",
    "Ostapenko J.": "Елена Остапенко",
    "Otte O.": "Оскар Отте",
    "Paolini J.": "Жасмин Паолини",
    "Parks A.": "Алисия Паркс",
    "Parrizas Diaz N.": "Акугуе Ноха Н.",
    "Parry D.": "Диана Парри",
    "Passaro F.": "Франческо Пассаро",
    "Pattinama Kerkhove L.": "Ван Асше Л.",
    "Paul T.": "Якуб Пауль",
    "Pavlyuchenkova A.": "Анастасия Павлюченкова",
    "Pegula J.": "Джессика Пегула",
    "Pella G.": "Гидо Пелья",
    "Pellegrino A.": "Андреа Пеллегрино",
    "Peniston R.": "Райан Пенистон",
    "Pera B.": "Бернарда Пера",
    "Peterson R.": "Петерсон Р.",
    "Petkovic A.": "Андреа Петкович",
    "Pigato L.": "Лиза Пигато",
    "Pironkova T.": "Пиронкова Ц.",
    "Piros Z.": "Жомбор Пирош",
    "Pliskova Ka.": "Каролина Плишкова",
    "Pliskova Kr.": "Каролина Плишкова",
    "Podoroska N.": "Надя Подороска",
    "Polmans M.": "Марк Полманс",
    "Ponchet J.": "Джессика Понше",
    "Popyrin A.": "Алексей Попырин",
    "Pospisil V.": "Вашек Поспишил",
    "Potapova A.": "Анастасия Потапова",
    "Preston T.": "Престон Т.",
    "Prizmic D.": "Дино Призмич",
    "Purcell M.": "Макс Пёрселл",
    "Putintseva Y.": "Юлия Путинцева",
    "Querrey S.": "Куэрри С.",
    "Quinn E.": "Итан Куинн",
    "Raducanu E.": "Радукану Э.",
    "Raina A.": "Анкита Раина",
    "Rakhimova K.": "Камилла Рахимова",
    "Rakotomanga Rajaonah T.": "Ван Рейтховен Т.",
    "Ramos-Vinolas A.": "Альберт Рамос-Виньолас",
    "Raonic M.": "Милош Раонич",
    "Riedi L.": "Леандро Риеди",
    "Rinderknech A.": "Артур Риндеркнеш",
    "Riske A.": "Риске А.",
    "Rocha H.": "Франсишку Роча",
    "Rodina E.": "Евгения Родина",
    "Rodionov J.": "Родионов Ю.",
    "Rogers S.": "Шелби Роджерс",
    "Romero Gormaz L.": "Ван Асше Л.",
    "Royer V.": "Валентен Ройер",
    "Rublev A.": "Рублев А.",
    "Rune H.": "Руне Х.",
    "Rus A.": "Аранча Рус",
    "Ruse E.G.": "Елена-Габрьела Русе",
    "Ruud C.": "Каспер Рууд",
    "Ruusuvuori E.": "Руусувуори Э.",
    "Ruzic A.": "Антония Ружич",
    "Rybakina E.": "Елена Рыбакина",
    "Sabalenka A.": "Адитья Вишал Балсекар",
    "Sachko V.": "Виталий Сачко",
    "Safiullin R.": "Роман Сафиуллин",
    "Sakamoto R.": "Рэй Сакамото",
    "Sakkari M.": "Мария Саккари",
    "Samsonova L.": "Людмила Самсонова",
    "Sanders S.": "Сандерс С.",
    "Sandgren T.": "Сандгрен Т.",
    "Sasnovich A.": "Александра Саснович",
    "Saville D.": "Дарья Сэвилл",
    "Sawangkaew M.": "Мананчая Савангкаев",
    "Schmiedlova A.": "Анна Каролина Шмидлова",
    "Schwartzman D.": "Диего Шварцман",
    "Sebov K.": "Катерин Себов",
    "Sekulic P.": "Филип Секулич",
    "Selekhmeteva O.": "Оксана Селехметева",
    "Seppi A.": "Андреас Сеппи",
    "Sevastova A.": "Анастасия Севастова",
    "Seyboth Wild T.": "Сейбот Уилд Т.",
    "Shang J.": "Шао Ю Шань",
    "Shapovalov D.": "Денис Шаповалов",
    "Sharma A.": "Астра Шарма",
    "Shelbayh A.": "Абдула Шелбах",
    "Shelton B.": "Бэн Шелтон",
    "Sherif M.": "Майар Шериф",
    "Shevchenko A.": "Александр Шевченко",
    "Shi H.": "Хань Ши",
    "Shibahara E.": "Сибахара Е.",
    "Shnaider D.": "Диана Шнайдер",
    "Shvedova Y.": "Шведова Я.",
    "Shymanovich I.": "Ирина Шиманович",
    "Siegemund L.": "Зигемунд Л.",
    "Sierra S.": "Солана Сиерра",
    "Simon G.": "Жиль Симон",
    "Siniakova K.": "Катерина Синякова",
    "Sinner J.": "Синнер Я.",
    "Skatov T.": "Тимофей Скатов",
    "Smith C.": "Алана Смит",
    "Snigur D.": "Дария Снигур",
    "Sock J.": "Джек Сок",
    "Sonego L.": "Лоренцо Сонего",
    "Sonmez Z.": "Зейнеп Сонмез",
    "Sorribes Tormo S.": "Соррибес Тормо С.",
    "Sousa J.": "Соуса Ж.",
    "Spizzirri E.": "Элиот Спиццирри",
    "Sramkova R.": "Ребекка Срамкова",
    "Stakusic M.": "Марина Стакушич",
    "Starodubtseva Y.": "Юлия Стародубцева",
    "Stearns P.": "Пэйтон Стернс",
    "Stefanini L.": "Лукреция Стефанини",
    "Stephens S.": "Слоан Стивенс",
    "Stevanovic N.": "Наталия Стеванович",
    "Stojanovic N.": "Нина Стоянович",
    "Stosur S.": "Стосур С.",
    "Stricker D.": "Стрикер Д.С.",
    "Struff J.L.": "Штруфф Я.-Л.",
    "Strycova B.": "Барбора Стрыцова",
    "Sun L.": "Лулу Сунь",
    "Svajda Z.": "Закари Свайда",
    "Svitolina E.": "Свитолина Э.",
    "Svrcina D.": "Далибор Сврцина",
    "Swan K.": "Ан К.",
    "Taberner C.": "Карлос Табернер",
    "Tabilo A.": "Алехандро Табило",
    "Tabur C.": "Клеман Табур",
    "Tagger L.": "Лилли Таггер",
    "Tan H.": "Тан Х.",
    "Tauson C.": "Клара Таусон",
    "Thiem D.": "Доминик Тим",
    "Thompson J.": "Джордан Томпсон",
    "Tiafoe F.": "Фангран Тиан",
    "Tien L.": "Лёрнер Тьен",
    "Tig P.M.": "Патрисия Мария Тиг",
    "Timofeeva M.": "Мария Тимофеева",
    "Tirante T.A.": "Тиаго Агустин Тиранте",
    "Tjen J.": "Дженис Тьен",
    "Todoni A.": "Анка Алексия Тодони",
    "Tomic B.": "Бернард Томич",
    "Tomljanovic A.": "Айла Томлянович",
    "Tomova V.": "Виктория Томова",
    "Townsend T.": "Тейлор Таунсенд",
    "Travaglia S.": "Стефано Травалья",
    "Trevisan M.": "Тревисан Мар.",
    "Troicki V.": "Троицки В.",
    "Trungelliti M.": "Марко Трунхельити",
    "Tseng C.H.": "Чо Ицзен",
    "Tsitsipas S.": "Стефанос Циципас",
    "Tsonga J.W.": "Тсонга Дж.",
    "Tsurenko L.": "Леся Цуренко",
    "Uchijima M.": "Моюка Утидзима",
    "Uchiyama Y.": "Ясутака Утияма",
    "Udvardy P.": "Панна Удварди",
    "Vacherot V.": "Валентин Вашеро",
    "Valentova T.": "Тереза Валентова",
    "Valkusz M.": "Мате Валькус",
    "Vallejo D.": "Дуарте Вале",
    "Van Assche L.": "Ван Асше Л.",
    "Van De Zandschulp B.": "Ван Де Зандшульп Б.",
    "Van Rijthoven T.": "Ван Рейтховен Т.",
    "Van Uytvanck A.": "Большова Задойнова А.",
    "Vandeweghe C.": "Вандевеге К.",
    "Varillas J. P.": "Мартинес Портеро П.",
    "Varillas J.P.": "Варильяс Х.П.",
    "Vavassori A.": "Андреа Вавассори",
    "Vekic D.": "Векич Д.",
    "Vesely J.": "Веселы И.",
    "Vickery S.": "Викери С.",
    "Vidmanova D.": "Дарья Видманова",
    "Vilella Martinez M.": "Вилелья Мартинес М.",
    "Virtanen O.": "Отто Виртанен",
    "Volynets K.": "Волынец К.",
    "Von Deichmann K.": "Алькарас Гарфия К.",
    "Vondrousova M.": "Вондроусова М.",
    "Vukic A.": "Александар Вукич",
    "Waltert S.": "Вальтерт С.",
    "Walton A.": "Адам Уолтон",
    "Wang Q.": "Вивиан Янг",
    "Wang Xin.": "Вивиан Янг",
    "Wang Xiy.": "Вивиан Янг",
    "Wang Y.": "Вивиан Янг",
    "Watanuki Y.": "Ёсукэ Ватануки",
    "Wawrinka S.": "Вавринка С.",
    "Wickmayer Y.": "Янина Викмайер",
    "Williams S.": "Серена Уильямс",
    "Williams V.": "Венус Уильямс",
    "Wolf J.J.": "Вольф Дж.",
    "Wong C.": "Йеспер Де Йонг",
    "Yastremska D.": "Даяна Ястремская",
    "Yevseyev D.": "Денис Евсеев",
    "Ymer E.": "Имер Э.",
    "Ymer M.": "Имер М.",
    "Yuan Y.": "Кайя Юван",
    "Zakharova A.": "Анастасия Захарова",
    "Zanevska M.": "Заневская М.",
    "Zapata Miralles B.": "Ван Де Зандшульп Б.",
    "Zarazua R.": "Рената Сарасуа",
    "Zeppieri G.": "Джулио Цеппьери",
    "Zhang S.": "Джейсон Джанг",
    "Zhang Zh.": "Джейсон Джанг",
    "Zhao C.": "Кэрол Чжао",
    "Zheng M.": "Майкл Чжэн",
    "Zheng Q.": "Берфу Дженгиз",
    "Zheng S.": "Берфу Дженгиз",
    "Zhu L.": "Эван Чжу",
    "Zhukayev B.": "Бейбит Жукаев",
    "Zidansek T.": "Зидансек Т.",
    "Zverev A.": "Александр Зверев",
    "Zvonareva V.": "Вера Звонарева",
}

# Не смапированные (требуют ручной проверки):
# Bouzas Maneiro J. -> Бассольс Рибера М. (65)
# De Jong J. -> Да Сильва Фик Г. (65)
# Hussey G. -> Габриэла Се (65)
# Jacquemot E. -> Эльза Жакмо (55)
# Jacquet K. -> Хазем Нау (55)
# Jarry N. -> Маррей Э. (73)
# Jeanjean L. -> Ли Энн (70)
# Jimenez V. -> Менезес Ж.Л. (71)
# Joint M. -> Магда Линетт (70)
# Kym J. -> Жером Ким (67)
# Majchrzak K. -> Камиль Майхшак (71)
# McNally C. -> Кэтрин Макналли (67)
# Mccabe J. -> Майер Л. (55)
# Mchale C. -> Симона Халеп (67)
# Mcnally C. -> Кэтрин Макналли (67)
# Niemeier J. -> Имер М. (67)
# O Connell C. -> Оже Альяссим Ф. (65)
# Paire B. -> Джульета Пареха (67)
# Paquet C. -> Люка Пуйе (60)
# Pinnington Jones J. -> Панчеко Мендес Р. (65)